# Generated by Django 3.1.1 on 2020-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto_celulares',
            fields=[
                ('id_producto_c', models.AutoField(db_column='id_producto_c', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('Foto_producto_c', models.ImageField(blank=True, null=True, upload_to='fotos_c')),
            ],
        ),
        migrations.CreateModel(
            name='producto_destacado',
            fields=[
                ('id_producto_d', models.AutoField(db_column='id_producto_d', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('Foto_producto_d', models.ImageField(blank=True, null=True, upload_to='fotos_d')),
            ],
        ),
        migrations.CreateModel(
            name='producto_notebook',
            fields=[
                ('id_producto_n', models.AutoField(db_column='id_producto_n', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('Foto_producto_n', models.ImageField(blank=True, null=True, upload_to='fotos_n')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=20, null=True)),
                ('dirrecion', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=13, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Contraseña', models.CharField(blank=True, max_length=50, null=True)),
                ('Pais', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('Numero_Documento', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
