# Generated by Django 3.1.1 on 2020-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_celulares',
            name='precio',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto_destacado',
            name='precio',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto_notebook',
            name='precio',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
