# Generated by Django 3.1.1 on 2020-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201023_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto_d', models.AutoField(db_column='id_producto_d', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('Foto_producto_d', models.ImageField(blank=True, null=True, upload_to='fotos_d')),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('destacado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='producto_celulares',
        ),
        migrations.DeleteModel(
            name='producto_destacado',
        ),
        migrations.DeleteModel(
            name='producto_notebook',
        ),
    ]
